[tasks.build]
command = "cargo"
args = ["+nightly", "xbuild"]

[tasks.run]
command = "cargo"
args = ["+nightly", "xrun"]

[tasks.test]
command = "cargo"
args = ["+nightly", "xtest"]

[tasks.build_test]
dependencies = [
    "build",
    "test"
]