[tasks.build]
toolchain = "nightly"
command = "cargo"
args = ["xbuild"]

[tasks.build_release]
toolchain = "nightly"
command = "cargo"
args = ["bootimage", "--release"]

[tasks.run]
toolchain = "nightly"
command = "cargo"
args = ["xrun"]

[tasks.test]
toolchain = "nightly"
command = "cargo"
args = ["xtest"]

[tasks.build_test]
dependencies = [
    "build",
    "test"
]