name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.5
      with:
        toolchain: nightly
        components: rust-src, llvm-tools-preview

    - name: Install cargo-make
      uses: davidB/rust-cargo-make@v1.2.1

    - name: Download cargo-xbuild
      uses: carlosperate/download-file-action@v1.0.0
      with:
        file-url: https://github.com/aunetx/files_utils/blob/master/cargo-xbuild.7z?raw=true
        file-name: cargo-xbuild.7z

    - name: Extract cargo-xbuild
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: cargo-xbuild.7z
        pathTarget: /home/runner/.cargo/bin

    - name: Build
      run: cargo +nightly xbuild
      
    - name: Get Package
      uses: mstksg/get-package@v1
      with:
        apt-get: qemu
      
    - name: Install bootimage
      run: cargo install bootimage

    - name: Test
      run: cargo +nightly xtest
